# Generated by Django 2.0 on 2020-04-18 11:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_mgmt', '0002_grouptbl_userfriendstbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_flag', models.BooleanField(default=True)),
                ('message', models.TextField(default='')),
                ('public_flag', models.IntegerField(default=0)),
                ('is_read_flag', models.BooleanField(default=False)),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('peer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_user', to='user_mgmt.UserTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_user', to='user_mgmt.UserTbl')),
            ],
        ),
        migrations.CreateModel(
            name='GroupChatRecordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField(default='')),
                ('record_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.GroupTbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.UserTbl')),
            ],
        ),
    ]
