# Generated by Django 2.0 on 2020-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecordtbl',
            name='public_flag',
            field=models.IntegerField(default=0),
        ),
    ]
