# Generated by Django 2.0 on 2020-04-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_chat', '0003_auto_20200419_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecorddetailtbl',
            name='peer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.UserTbl'),
        ),
    ]
