# Generated by Django 2.0 on 2020-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_chat', '0005_auto_20200419_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecorddetailtbl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatrecordtbl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupchatrecordtbl',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
