# Generated by Django 2.0 on 2020-04-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_chat', '0006_auto_20200419_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecorddetailtbl',
            name='peer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_record_detail_peer_user', to='user_mgmt.UserTbl'),
        ),
        migrations.AlterField(
            model_name='chatrecordtbl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_record_user', to='user_mgmt.UserTbl'),
        ),
    ]
